apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
  - httproute.yaml
  - matter-pvc.yaml
  - matter-service.yaml
  - matter-statefulset.yaml
