apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: talos-worker-03
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  storage.home.antonu.org/synology-iscsi: "true"
  hardware.home.antonu.org/raspbee2: "true"
