apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anki-sync-credentials
  namespace: anki-sync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: home-cloud-vault
    kind: SecretStore
  target:
    name: anki-sync-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: SYNC_USER1
      remoteRef:
        key: anki-sync/credentials
        property: SYNC_USER1
