apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anki-sync-data
  namespace: anki-sync
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-block
  resources:
    requests:
      storage: 5Gi
