apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-credentials
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: home-cloud-vault
    kind: SecretStore
  target:
    name: mikrotik-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: MIKROTIK_BASEURL
      remoteRef:
        key: external-dns/mikrotik-credentials
        property: MIKROTIK_BASEURL
    - secretKey: MIKROTIK_USERNAME
      remoteRef:
        key: external-dns/mikrotik-credentials
        property: MIKROTIK_USERNAME
    - secretKey: MIKROTIK_PASSWORD
      remoteRef:
        key: external-dns/mikrotik-credentials
        property: MIKROTIK_PASSWORD
