apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: external-dns
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.22.0
      helm:
        releaseName: external-dns
        skipCrds: true
        valueFiles:
          - $values/kubernetes/external-dns/values.yaml
    - repoURL: https://github.com/antonu17/home-infra.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/antonu17/home-infra.git
      targetRevision: main
      path: kubernetes/external-dns/policy
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
