apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deconz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: deCONZ and Phoscon for the RaspBee II coordinator
  sourceRepos:
    - https://github.com/antonu17/home-infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: deconz
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deconz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: deconz
  source:
    repoURL: https://github.com/antonu17/home-infra.git
    targetRevision: main
    path: kubernetes/apps/deconz
  destination:
    server: https://kubernetes.default.svc
    namespace: deconz
