apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: external-secrets chart installation and namespaced Vault secret synchronization.
  sourceRepos:
    - https://github.com/antonu17/home-infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: external-secrets
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: external-secrets
  source:
    repoURL: https://github.com/antonu17/home-infra.git
    targetRevision: main
    path: kubernetes/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
