apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  sourceRepos:
    - https://github.com/antonu17/home-infra.git
    - https://kubernetes-sigs.github.io/external-dns/
  destinations:
    - server: https://kubernetes.default.svc
      namespace: external-dns
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: external-dns
  source:
    repoURL: https://github.com/antonu17/home-infra.git
    targetRevision: main
    path: kubernetes/external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
