apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grocy
  namespace: argocd
spec:
  description: grocy with retained Synology storage
  sourceRepos:
    - https://github.com/antonu17/home-infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: grocy
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grocy
  namespace: argocd
spec:
  project: grocy
  source:
    repoURL: https://github.com/antonu17/home-infra.git
    targetRevision: main
    path: kubernetes/apps/grocy
  destination:
    server: https://kubernetes.default.svc
    namespace: grocy
