apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mealie
  namespace: argocd
spec:
  description: mealie with retained Synology storage
  sourceRepos:
    - https://github.com/antonu17/home-infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: mealie
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
  namespace: argocd
spec:
  project: mealie
  source:
    repoURL: https://github.com/antonu17/home-infra.git
    targetRevision: main
    path: kubernetes/apps/mealie
  destination:
    server: https://kubernetes.default.svc
    namespace: mealie
