apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  dsm: "pulsar.home.antonu.org"
  location: "/volume3"
  protocol: "iscsi"
  fsType: "ext4"
  enableFuaSyncCache: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
