apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-antonu-org
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: home-antonu-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - home.antonu.org
    - '*.home.antonu.org'
