apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-data
  namespace: deconz
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-block
  resources:
    requests:
      storage: 5Gi
