apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adsb-config
  namespace: adsb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: home-cloud-vault
    kind: SecretStore
  target:
    name: adsb-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: LAT
      remoteRef:
        key: adsb/feeders
        property: LAT
    - secretKey: LON
      remoteRef:
        key: adsb/feeders
        property: LON
    - secretKey: FLIGHTAWARE_FEEDER_ID
      remoteRef:
        key: adsb/feeders
        property: FLIGHTAWARE_FEEDER_ID
    - secretKey: FR24KEY
      remoteRef:
        key: adsb/feeders
        property: FR24KEY
