apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-eso
  namespace: adsb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-vault-token
  namespace: adsb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups: [""]
    resources: [serviceaccounts/token]
    resourceNames: [vault-eso]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-vault-token
  namespace: adsb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-vault-token
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: home-cloud-vault
  namespace: adsb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  provider:
    vault:
      server: https://vault.home.antonu.org
      path: home-cloud
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-home-cloud
          role: eso-adsb
          serviceAccountRef:
            name: vault-eso
            audiences: [vault]
